### ISSUE TITLE
It doesn't work with Angular 13 and typeacript version 4.6.3

### ISSUE THREAD

**Issue by ggu123456** [microsoftgraph/microsoft-graph-docs#18155]
I'm using VisulStudio 2022 to create an Angular projet, which has Angular v13 and TypeScript 4.6.3. 
I followed the steps in this doc, but when I run the app , I got the following error. it seems the graph control doesn't work with angular 13 and typeScript 4.6.3

Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:222:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'HTMLElement & FASTElement' and 'DelegatesARIALink'.
  Named property 'ariaAtomic' of types 'HTMLElement & FASTElement' and 'DelegatesARIALink' are not identical.

222 export declare interface Anchor extends StartEnd, DelegatesARIALink {
                             ~~~~~~


Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:222:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'HTMLElement & FASTElement' and 'DelegatesARIALink'.
  Named property 'ariaBusy' of types 'HTMLElement & FASTElement' and 'DelegatesARIALink' are not identical.

222 export declare interface Anchor extends StartEnd, DelegatesARIALink {
                             ~~~~~~

Error: node_modules/@microsoft/fast-foundation/dist/fast-foundation.d.ts:222:26 - error TS2320: Interface 'Anchor' cannot simultaneously extend types 'HTMLElement & FASTElement' and 'DelegatesARIALink'.
  Named property 'ariaDisabled' of types 'HTMLElement & FASTElement' and 'DelegatesARIALink' are not identical.

222 export declare interface Anchor extends StartEnd, DelegatesARIALink {
                             ~~~~~~


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3952371-7287-cba7-5c09-e437c09a0a14
* Version Independent ID: d29c803a-c1f5-19fe-f821-5a447f1c3e04
* Content: [Use the Microsoft Graph Toolkit with Angular - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular)
* Content Source: [concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toolkit/get-started/use-toolkit-with-angular.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @sebastienlevert
* Microsoft Alias: **MSGraphDocsVteam**
